# Generated by Django 2.2 on 2021-03-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_remove_blog_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(null=True, verbose_name='дата публикции'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
