# Generated by Django 2.2 on 2021-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20210315_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='fileholder',
            name='image',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
