# Generated by Django 2.2 on 2021-03-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_auto_20210316_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(null=True, upload_to='avatar_profile/'),
        ),
    ]
